//! Character code tables (`ESC t n`). Bytes 0x20–0x7E are ASCII in every table; the upper
//! half comes from `codepage_tables.rs`, generated by `scripts/codepages.py`.

use super::codepage_tables as tables;

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum CodePage {
    Cp437,
    Cp850,
    Cp860,
    Cp863,
    Cp865,
    Wpc1252,
    Cp866,
    Cp852,
    Cp858,
}

impl CodePage {
    /// Epson's factory default, used until `ESC t` selects another (decision 4).
    pub const DEFAULT: Self = Self::Cp437;

    /// The table `ESC t n` selects. `None` for tables the emulator does not have (Katakana,
    /// Thai…): the printer keeps the current one.
    pub fn from_table(n: u8) -> Option<Self> {
        Some(match n {
            0 => Self::Cp437,
            2 => Self::Cp850,
            3 => Self::Cp860,
            4 => Self::Cp863,
            5 => Self::Cp865,
            16 => Self::Wpc1252,
            17 => Self::Cp866,
            18 => Self::Cp852,
            19 => Self::Cp858,
            _ => return None,
        })
    }

    pub fn decode(self, byte: u8) -> char {
        if byte < 0x80 {
            return char::from(byte);
        }
        self.upper()[usize::from(byte - 0x80)]
    }

    /// The byte for `character` in this table, `?` when the table does not have it.
    pub fn encode(self, character: char) -> u8 {
        if (' '..='~').contains(&character) {
            return character as u8;
        }
        self.upper()
            .iter()
            .position(|&candidate| candidate == character)
            .map_or(b'?', |index| 0x80 + index as u8)
    }

    /// The `n` of the `ESC t n` that selects this table.
    pub fn table(self) -> u8 {
        match self {
            Self::Cp437 => 0,
            Self::Cp850 => 2,
            Self::Cp860 => 3,
            Self::Cp863 => 4,
            Self::Cp865 => 5,
            Self::Wpc1252 => 16,
            Self::Cp866 => 17,
            Self::Cp852 => 18,
            Self::Cp858 => 19,
        }
    }

    /// Short name for people: `CP437`, `WPC1252`…
    pub fn name(self) -> &'static str {
        match self {
            Self::Cp437 => "CP437",
            Self::Cp850 => "CP850",
            Self::Cp860 => "CP860",
            Self::Cp863 => "CP863",
            Self::Cp865 => "CP865",
            Self::Wpc1252 => "WPC1252",
            Self::Cp866 => "CP866",
            Self::Cp852 => "CP852",
            Self::Cp858 => "CP858",
        }
    }

    fn upper(self) -> &'static [char; 128] {
        match self {
            Self::Cp437 => &tables::CP437,
            Self::Cp850 => &tables::CP850,
            Self::Cp860 => &tables::CP860,
            Self::Cp863 => &tables::CP863,
            Self::Cp865 => &tables::CP865,
            Self::Wpc1252 => &tables::WPC1252,
            Self::Cp866 => &tables::CP866,
            Self::Cp852 => &tables::CP852,
            Self::Cp858 => &tables::CP858,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::CodePage;

    fn decode(page: CodePage, bytes: &[u8]) -> String {
        bytes.iter().map(|&byte| page.decode(byte)).collect()
    }

    #[test]
    fn ascii_is_the_same_everywhere() {
        for n in 0..=255 {
            if let Some(page) = CodePage::from_table(n) {
                assert_eq!(decode(page, b"Total: $ 12,50"), "Total: $ 12,50");
            }
        }
    }

    #[test]
    fn portuguese_and_spanish_accents() {
        // "Ação Café Pão Ñandú" in each page's own bytes.
        assert_eq!(
            decode(CodePage::Cp850, b"A\x87\xc6o Caf\x82 P\xc6o \xa5and\xa3"),
            "Ação Café Pão Ñandú"
        );
        assert_eq!(
            decode(CodePage::Cp860, b"A\x87\x84o Caf\x82 P\x84o \xa5and\xa3"),
            "Ação Café Pão Ñandú"
        );
        assert_eq!(
            decode(CodePage::Wpc1252, b"A\xe7\xe3o Caf\xe9 P\xe3o \xd1and\xfa"),
            "Ação Café Pão Ñandú"
        );
    }

    #[test]
    fn euro_sign_and_box_drawing() {
        assert_eq!(CodePage::Cp858.decode(0xd5), '€');
        assert_eq!(CodePage::Wpc1252.decode(0x80), '€');
        assert_eq!(CodePage::Cp437.decode(0xc4), '─');
        assert_eq!(CodePage::Cp866.decode(0x80), 'А');
        assert_eq!(CodePage::Cp852.decode(0xa5), 'ą');
    }

    #[test]
    fn table_numbers_round_trip() {
        for n in 0..=255 {
            if let Some(page) = CodePage::from_table(n) {
                assert_eq!(page.table(), n, "{page:?}");
            }
        }
    }

    #[test]
    fn undefined_bytes_and_unknown_tables() {
        assert_eq!(CodePage::Wpc1252.decode(0x81), '\u{fffd}');
        assert_eq!(CodePage::from_table(1), None, "Katakana is not supported");
        assert_eq!(CodePage::from_table(b'0'), None);
    }

    #[test]
    fn encodes_back_to_the_same_bytes() {
        for page in [
            CodePage::Cp437,
            CodePage::Cp850,
            CodePage::Wpc1252,
            CodePage::Cp866,
        ] {
            for byte in (0x20..0x7f).chain(0x80..=0xff) {
                let character = page.decode(byte);
                if character != '\u{fffd}' {
                    assert_eq!(
                        page.decode(page.encode(character)),
                        character,
                        "{page:?} {byte:#x}"
                    );
                }
            }
        }
        assert_eq!(CodePage::Cp437.encode('€'), b'?', "CP437 has no euro sign");
        assert_eq!(CodePage::Cp858.encode('€'), 0xd5);
    }
}
