//! Character code tables (`ESC t n`). Bytes 0x20–0x7E are ASCII in every table; the upper
//! half comes from `codepage_tables.rs`, generated by `scripts/codepages.py`.

use super::codepage_tables as tables;

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum CodePage {
    Cp437,
    Cp850,
    Cp860,
    Cp863,
    Cp865,
    Wpc1252,
    Cp866,
    Cp852,
    Cp858,
}

impl CodePage {
    /// Epson's factory default, used until `ESC t` selects another (decision 4).
    pub const DEFAULT: Self = Self::Cp437;

    /// The table `ESC t n` selects. `None` for tables the emulator does not have (Katakana,
    /// Thai…): the printer keeps the current one.
    pub fn from_table(n: u8) -> Option<Self> {
        Some(match n {
            0 => Self::Cp437,
            2 => Self::Cp850,
            3 => Self::Cp860,
            4 => Self::Cp863,
            5 => Self::Cp865,
            16 => Self::Wpc1252,
            17 => Self::Cp866,
            18 => Self::Cp852,
            19 => Self::Cp858,
            _ => return None,
        })
    }

    pub fn decode(self, byte: u8) -> char {
        if byte < 0x80 {
            return char::from(byte);
        }
        let upper = match self {
            Self::Cp437 => &tables::CP437,
            Self::Cp850 => &tables::CP850,
            Self::Cp860 => &tables::CP860,
            Self::Cp863 => &tables::CP863,
            Self::Cp865 => &tables::CP865,
            Self::Wpc1252 => &tables::WPC1252,
            Self::Cp866 => &tables::CP866,
            Self::Cp852 => &tables::CP852,
            Self::Cp858 => &tables::CP858,
        };
        upper[usize::from(byte - 0x80)]
    }
}

#[cfg(test)]
mod tests {
    use super::CodePage;

    fn decode(page: CodePage, bytes: &[u8]) -> String {
        bytes.iter().map(|&byte| page.decode(byte)).collect()
    }

    #[test]
    fn ascii_is_the_same_everywhere() {
        for n in 0..=255 {
            if let Some(page) = CodePage::from_table(n) {
                assert_eq!(decode(page, b"Total: $ 12,50"), "Total: $ 12,50");
            }
        }
    }

    #[test]
    fn portuguese_and_spanish_accents() {
        // "Ação Café Pão Ñandú" in each page's own bytes.
        assert_eq!(
            decode(CodePage::Cp850, b"A\x87\xc6o Caf\x82 P\xc6o \xa5and\xa3"),
            "Ação Café Pão Ñandú"
        );
        assert_eq!(
            decode(CodePage::Cp860, b"A\x87\x84o Caf\x82 P\x84o \xa5and\xa3"),
            "Ação Café Pão Ñandú"
        );
        assert_eq!(
            decode(CodePage::Wpc1252, b"A\xe7\xe3o Caf\xe9 P\xe3o \xd1and\xfa"),
            "Ação Café Pão Ñandú"
        );
    }

    #[test]
    fn euro_sign_and_box_drawing() {
        assert_eq!(CodePage::Cp858.decode(0xd5), '€');
        assert_eq!(CodePage::Wpc1252.decode(0x80), '€');
        assert_eq!(CodePage::Cp437.decode(0xc4), '─');
        assert_eq!(CodePage::Cp866.decode(0x80), 'А');
        assert_eq!(CodePage::Cp852.decode(0xa5), 'ą');
    }

    #[test]
    fn undefined_bytes_and_unknown_tables() {
        assert_eq!(CodePage::Wpc1252.decode(0x81), '\u{fffd}');
        assert_eq!(CodePage::from_table(1), None, "Katakana is not supported");
        assert_eq!(CodePage::from_table(b'0'), None);
    }
}
