"""Generates src/escpos/codepage_tables.rs: the upper half (0x80-0xFF) of each code page
the emulator supports, from Python's codecs (built from the Unicode Consortium's mapping
files). Run from src-tauri/: python3 scripts/codepages.py > src/escpos/codepage_tables.rs
"""

# Epson ESC t numbers → Python codec.
PAGES = [
    ("CP437", "cp437", 0),
    ("CP850", "cp850", 2),
    ("CP860", "cp860", 3),
    ("CP863", "cp863", 4),
    ("CP865", "cp865", 5),
    ("WPC1252", "cp1252", 16),
    ("CP866", "cp866", 17),
    ("CP852", "cp852", 18),
    ("CP858", "cp858", 19),
]

print("// Generated by scripts/codepages.py. Do not edit by hand.")
print("// Upper half (0x80-0xFF) of each code page; bytes the page leaves undefined are U+FFFD.")
for name, codec, table in PAGES:
    chars = []
    for byte in range(0x80, 0x100):
        try:
            chars.append(bytes([byte]).decode(codec))
        except UnicodeDecodeError:
            chars.append("�")
    print()
    print(f"/// ESC t {table}.")
    print("#[rustfmt::skip]")
    print(f"pub const {name}: [char; 128] = [")
    for row in range(0, 128, 8):
        cells = ", ".join(f"'\\u{{{ord(c):04x}}}'" for c in chars[row:row + 8])
        print(f"    {cells},")
    print("];")
